<HTML>
<HEAD>
<meta charset="UTF-8">
<title>HospitalizeFlowException - corda</title>
<link rel="stylesheet" href="../../../style.css">
</HEAD>
<BODY>
<a href="../../index.html">corda</a>&nbsp;/&nbsp;<a href="../index.html">net.corda.core.flows</a>&nbsp;/&nbsp;<a href="./index.html">HospitalizeFlowException</a><br/>
<br/>
<h1>HospitalizeFlowException</h1>
<code><span class="keyword">open</span> <span class="keyword">class </span><span class="identifier">HospitalizeFlowException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="../../net.corda.core/-corda-runtime-exception/index.html"><span class="identifier">CordaRuntimeException</span></a></code>
<p>This exception allows a flow to pass itself to the flow hospital. Once the flow reaches
the hospital it will determine how to progress depending on what <a href="../../net.corda.core/-corda-runtime-exception/cause.html">cause</a>s the exception wraps.
Assuming there are no important wrapped exceptions, throwing a <a href="./index.html">HospitalizeFlowException</a>
will place the flow in overnight observation, where it will be replayed at a later time.</p>
<h3>Constructors</h3>
<table>
<tbody>
<tr>
<td>
<h4><a href="-init-.html">&lt;init&gt;</a></h4>
</td>
<td>
<code><span class="identifier">HospitalizeFlowException</span><span class="symbol">(</span><span class="identifier" id="net.corda.core.flows.HospitalizeFlowException$<init>(kotlin.String)/message">message</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-string/index.html"><span class="identifier">String</span></a><span class="symbol">?</span><span class="symbol">)</span></code><br/>
<code><span class="identifier">HospitalizeFlowException</span><span class="symbol">(</span><span class="identifier" id="net.corda.core.flows.HospitalizeFlowException$<init>(kotlin.Throwable)/cause">cause</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a><span class="symbol">?</span><span class="symbol">)</span></code><br/>
<code><span class="identifier">HospitalizeFlowException</span><span class="symbol">(</span><span class="symbol">)</span></code>
<p>This exception allows a flow to pass itself to the flow hospital. Once the flow reaches
the hospital it will determine how to progress depending on what <a href="../../net.corda.core/-corda-runtime-exception/cause.html">cause</a>s the exception wraps.
Assuming there are no important wrapped exceptions, throwing a <a href="./index.html">HospitalizeFlowException</a>
will place the flow in overnight observation, where it will be replayed at a later time.</p>
<code><span class="identifier">HospitalizeFlowException</span><span class="symbol">(</span><span class="identifier" id="net.corda.core.flows.HospitalizeFlowException$<init>(kotlin.String, kotlin.Throwable)/message">message</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-string/index.html"><span class="identifier">String</span></a><span class="symbol">?</span><span class="symbol">, </span><span class="identifier" id="net.corda.core.flows.HospitalizeFlowException$<init>(kotlin.String, kotlin.Throwable)/cause">cause</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a><span class="symbol">?</span><span class="symbol">)</span></code></td>
</tr>
</tbody>
</table>
</BODY>
</HTML>
