<HTML>
<HEAD>
<meta charset="UTF-8">
<title>TransactionResolutionException - corda</title>
<link rel="stylesheet" href="../../../style.css">
</HEAD>
<BODY>
<a href="../../index.html">corda</a>&nbsp;/&nbsp;<a href="../index.html">net.corda.core.contracts</a>&nbsp;/&nbsp;<a href="./index.html">TransactionResolutionException</a><br/>
<br/>
<h1>TransactionResolutionException</h1>
<code><span class="keyword">open</span> <span class="keyword">class </span><span class="identifier">TransactionResolutionException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="../../net.corda.core.flows/-flow-exception/index.html"><span class="identifier">FlowException</span></a></code>
<p>The node asked a remote peer for the transaction identified by <a href="hash.html">hash</a> because it is a dependency of a transaction
being resolved, but the remote peer would not provide it.</p>
<h3>Exceptions</h3>
<table>
<tbody>
<tr>
<td>
<p><a href="-unknown-parameters-exception/index.html">UnknownParametersException</a></p>
</td>
<td>
<code><span class="keyword">class </span><span class="identifier">UnknownParametersException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="./index.html"><span class="identifier">TransactionResolutionException</span></a></code>
<p>Thrown if a transaction specifies a set of parameters that aren't stored locally yet verification is requested.
This should never normally happen because before verification comes resolution, and if a peer can't provide a
new set of parameters, <a href="./index.html">TransactionResolutionException</a> will have already been thrown beforehand.</p>
</td>
</tr>
</tbody>
</table>
<h3>Constructors</h3>
<table>
<tbody>
<tr>
<td>
<p><a href="-init-.html">&lt;init&gt;</a></p>
</td>
<td>
<code><span class="identifier">TransactionResolutionException</span><span class="symbol">(</span><span class="identifier" id="net.corda.core.contracts.TransactionResolutionException$<init>(net.corda.core.crypto.SecureHash, kotlin.String)/hash">hash</span><span class="symbol">:</span>&nbsp;<a href="../../net.corda.core.crypto/-secure-hash/index.html"><span class="identifier">SecureHash</span></a><span class="symbol">, </span><span class="identifier" id="net.corda.core.contracts.TransactionResolutionException$<init>(net.corda.core.crypto.SecureHash, kotlin.String)/message">message</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-string/index.html"><span class="identifier">String</span></a>&nbsp;<span class="symbol">=</span>&nbsp;"Transaction resolution failure for $hash"<span class="symbol">)</span></code>
<p>The node asked a remote peer for the transaction identified by <a href="hash.html">hash</a> because it is a dependency of a transaction
being resolved, but the remote peer would not provide it.</p>
</td>
</tr>
</tbody>
</table>
<h3>Properties</h3>
<table>
<tbody>
<tr>
<td>
<p><a href="hash.html">hash</a></p>
</td>
<td>
<code><span class="keyword">val </span><span class="identifier">hash</span><span class="symbol">: </span><a href="../../net.corda.core.crypto/-secure-hash/index.html"><span class="identifier">SecureHash</span></a></code>
<p>Merkle root of the transaction being resolved, see <a href="../../net.corda.core.transactions/-wire-transaction/id.html">net.corda.core.transactions.WireTransaction.id</a></p>
</td>
</tr>
</tbody>
</table>
<h3>Inherited Properties</h3>
<table>
<tbody>
<tr>
<td>
<p><a href="../../net.corda.core.flows/-flow-exception/original-error-id.html">originalErrorId</a></p>
</td>
<td>
<code><span class="keyword">var </span><span class="identifier">originalErrorId</span><span class="symbol">: </span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-long/index.html"><span class="identifier">Long</span></a><span class="symbol">?</span></code>
<p>the ID backing <a href="../../net.corda.core.flows/-flow-exception/get-error-id.html">getErrorId</a>. If null it will be set dynamically by the flow framework when
    the exception is handled. This ID is propagated to counterparty flows, even when the <a href="../../net.corda.core.flows/-flow-exception/index.html">FlowException</a> is
    downgraded to an <a href="../../net.corda.core.flows/-unexpected-flow-end-exception/index.html">UnexpectedFlowEndException</a>. This is so the error conditions may be correlated later on.</p>
</td>
</tr>
</tbody>
</table>
<h3>Inherited Functions</h3>
<table>
<tbody>
<tr>
<td>
<p><a href="../../net.corda.core.flows/-flow-exception/get-error-id.html">getErrorId</a></p>
</td>
<td>
<code><span class="keyword">open</span> <span class="keyword">fun </span><span class="identifier">getErrorId</span><span class="symbol">(</span><span class="symbol">)</span><span class="symbol">: </span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-long/index.html"><span class="identifier">Long</span></a><span class="symbol">?</span></code></td>
</tr>
</tbody>
</table>
<h3>Extension Functions</h3>
<table>
<tbody>
<tr>
<td>
<p><a href="../../net.corda.core.utilities/kotlin.-any/context-logger.html">contextLogger</a></p>
</td>
<td>
<code><span class="keyword">fun </span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-any/index.html"><span class="identifier">Any</span></a><span class="symbol">.</span><span class="identifier">contextLogger</span><span class="symbol">(</span><span class="symbol">)</span><span class="symbol">: </span><span class="identifier">&lt;ERROR CLASS&gt;</span></code>
<p>When called from a companion object, returns the logger for the enclosing class.</p>
</td>
</tr>
</tbody>
</table>
<h3>Inheritors</h3>
<table>
<tbody>
<tr>
<td>
<p><a href="-unknown-parameters-exception/index.html">UnknownParametersException</a></p>
</td>
<td>
<code><span class="keyword">class </span><span class="identifier">UnknownParametersException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="./index.html"><span class="identifier">TransactionResolutionException</span></a></code>
<p>Thrown if a transaction specifies a set of parameters that aren't stored locally yet verification is requested.
This should never normally happen because before verification comes resolution, and if a peer can't provide a
new set of parameters, <a href="./index.html">TransactionResolutionException</a> will have already been thrown beforehand.</p>
</td>
</tr>
</tbody>
</table>
</BODY>
</HTML>
